apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiZ2hjci5pbyI6IHsKICAgICAgICAiYXV0aCI6ICJVbUZwYm1KdmR6UXlPbWRvY0Y5b1VUaGlXa3hJTjBselFuaDJjRk5zT1haSk0zZEVZazVGWjIxa2Eyc3dka1ppUkc4PSIKICAgICAgfQogICAgfQogIH0=
type: kubernetes.io/dockerconfigjson
